name: Mirror all branches with rewritten author (excluding .github)

on:
  push:
    branches:
      - '**'  # Trigger on all branches

  workflow_dispatch:  # Allow manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Exclude .github folder from all branches
        run: |
          git config --global user.email "hiranivipuls@gmail.com"
          git config --global user.name "Vipul Hirani"

          # Loop through all branches
          for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); do
            git checkout $branch

            # Create a single commit with all changes excluding .github
            git rm -r --cached .github  # Remove .github from the index
            git commit -m "commit " || true  # Create a single commit

            # Rewrite commit author
            git filter-repo --replace-commit-message '.*' 'Author: YourName <your-email>'
          done

      - name: Push all branches to client repo (excluding .github)
        env:
          GITHUB_TOKEN: ${{ secrets.CLIENT_REPO_PAT }}
        run: |
          git remote add client https://x-access-token:${GITHUB_TOKEN}@github.com/client-org/client-repo.git
          
          # Force push all branches while excluding .github
          git push --force --all client
          git push --force --tags client