name: Mirror Repo to Client (Change Author & Exclude .github)

on:
  push:
    branches:
      - '**'  # Trigger on any branch push

  workflow_dispatch:  # Allow manual execution

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Set new commit author
        run: |
          git config --global user.email "hiranivipuls@gmail.com"
          git config --global user.name "Vipul Hirani"

      - name: Remove .github folder and commit changes
        run: |
          # Remove .github folder from all branches
          if [ -d ".github" ]; then
            git rm -r --cached .github
            git commit -m "Removed .github workflows before mirroring" || echo "No changes to commit"
          fi

      - name: Rewrite commit author in all branches
        run: |
          for branch in $(git for-each-ref --format '%(refname:short)' refs/heads/); do
            git checkout $branch
            git commit --amend --no-edit --author="Vipul Hirani <hiranivipuls@gmail.com>"
          done


      - name: Push all branches to client repo (excluding .github)
        env:
          GITHUB_TOKEN: ${{ secrets.CLIENT_REPO_PAT }}
        run: |
          git remote add client https://x-access-token:${GITHUB_TOKEN}@github.com/client-org/client-repo.git
          
          # Force push all branches without .github
          git push --force --all client
          git push --force --tags client