name: Mirror Repo to Client (Change Author & Exclude .github)

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set new commit author
        run: |
          git config --global user.email "hiranivipuls@gmail.com"
          git config --global user.name "Vipul Hirani"

      - name: Remove .github folder
        run: |
          if [ -d ".github" ]; then
            git rm -r --cached .github
            git commit -m "Removed .github workflows before mirroring" || echo "No changes to commit"
          fi

      - name: Rewrite commit author in all branches
        run: |
          for branch in $(git for-each-ref --format '%(refname:short)' refs/heads/); do
            git checkout $branch
            git commit --amend --no-edit --author="Vipul Hirani <hiranivipuls@gmail.com>" || echo "No changes to amend in branch $branch"
          done

      - name: Set up remote and push to client repo
        env:
          GITHUB_TOKEN: ${{ secrets.CLIENT_REPO_PAT }}
        run: |
          echo "GITHUB_TOKEN is set: ${#GITHUB_TOKEN} characters long"
          
          CLIENT_REPO_URL="https://${GITHUB_TOKEN}@github.com/sending-ac/onboarding.git"

          # Ensure the remote is correct
          if git remote get-url client &>/dev/null; then
            git remote set-url client "$CLIENT_REPO_URL"
          else
            git remote add client "$CLIENT_REPO_URL"
          fi

          echo "Current remote URLs:"
          git remote -v

          # Push to the client repo
          git push --force --all client || echo "❌ Failed to push branches"
          git push --force --tags client || echo "❌ Failed to push tags"