name: Mirror Repo to Client (Change Author & Exclude .github)

on:
  push:
    branches:
      - '**'  # Trigger on any branch push

  workflow_dispatch:  # Allow manual execution

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Set new commit author
        run: |
          git config --global user.email "hiranivipuls@gmail.com"
          git config --global user.name "Vipul Hirani"

      - name: Remove .github folder and commit changes
        run: |
          # Remove .github folder from all branches
          if [ -d ".github" ]; then
            git rm -r --cached .github
            git commit -m "Removed .github workflows before mirroring" || echo "No changes to commit"
          fi

      - name: Rewrite commit author in all branches
        run: |
          for branch in $(git for-each-ref --format '%(refname:short)' refs/heads/); do
            git checkout $branch
            git commit --amend --no-edit --author="Vipul Hirani <hiranivipuls@gmail.com>"
          done


      - name: Push all branches to client repo
        env:
          GITHUB_TOKEN: ${{ secrets.CLIENT_REPO_PAT }}
        run: |
          # Authenticate with GitHub token
          git config --global credential.helper store
          echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Ensure remote doesn't already exist
          if ! git remote | grep -q "^client$"; then
            git remote add client https://github.com/sending-ac/onboarding.git
          fi
          
       
          # Force push all branches and tags to the client repo
          git push --force --all client || echo "Failed to push branches to client repo. Check if the repository exists and the token has access."
          git push --force --tags client || echo "Failed to push tags to client repo. Check if the repository exists and the token has access."