name: Mirror all branches with rewritten author (excluding .github)

on:
  push:
    branches:
      - '**'  # Trigger on all branches

  workflow_dispatch:  # Allow manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Remove .github folder from all branches
        run: |
          git config --global user.email "hiranivipuls@gmail.com"
          git config --global user.name "Vipul Hirani"

          # Loop through all branches
          for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); do
            git checkout $branch

            # Remove .github folder if it exists
            if [ -d ".github" ]; then
              git rm -r --cached .github
              git commit --amend --no-edit
            fi

            # Rewrite commit author
            git rebase -i --root
            git filter-repo --replace-commit-message '.*' 'Author: YourName <your-email>'
          done

      - name: Push all branches to client repo (excluding .github)
        env:
          GITHUB_TOKEN: ${{ secrets.CLIENT_REPO_PAT }}
        run: |
          git remote add client https://x-access-token:${GITHUB_TOKEN}@github.com:sending-ac/onboarding.git
          
          # Force push all branches without .github
          git push --force --all client
          git push --force --tags client